version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parking-dev
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    env_file:
      - .env
    command: ./gradlew bootRun --no-daemon

  postgres:
    image: postgres:16
    container_name: parking-db
    environment:
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_pass
      POSTGRES_DB: parking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: parking-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  gradle-cache: